CreatePO()
{
	web_save_timestamp_param("cp_time", LAST);
	//lr_output_message("Timestamp: %s", lr_eval_string("{cp_time}"));
		web_set_sockets_option("CLOSE_KEEPALIVE_CONNECTIONS","1");
	lr_start_transaction("CP48_CreatePO");

	web_submit_data("AjaxOrderShipInfoUpdate", 
		"Action=https://{p_hostName}/us-en/shop/AjaxOrderShipInfoUpdate", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html;charset=UTF-8", 
		"Snapshot=t238.inf", 
		"Mode=HTML", 
		"EncodeAtSign=YES", 
		ITEMDATA, 
		"Name=editAddress", "Value=true", ENDITEM, 
		"Name=nickName", "Value=EStore_PSA_CreatePO_{cp_time}", ENDITEM,
		"Name=addressId", "Value={cp_addressId}", ENDITEM, 
		"Name=firstName", "Value=PerfFirstSMB", ENDITEM, 
		"Name=lastName", "Value=PerfLastSMB", ENDITEM, 
		"Name=organizationName", "Value={cp_companyName}", ENDITEM, 
		"Name=address1", "Value=PerfAddress1", ENDITEM, 
		"Name=address2", "Value=", ENDITEM, 
		"Name=city", "Value={p_city}", ENDITEM, 
		"Name=state", "Value={p_state}", ENDITEM,  
		"Name=zipCode", "Value={p_zipCode}", ENDITEM, 
		"Name=country", "Value=US", ENDITEM, 
		"Name=email1", "Value={cp_userEmail}", ENDITEM, 
		"Name=phone1", "Value=1234567890", ENDITEM, 
		"Name=isResidenceAddr", "Value=true", ENDITEM, 
		"Name=isSmbOrder", "Value=true", ENDITEM, 
		"Name=shipModeId", "Value=12056", ENDITEM, 
		"Name=authToken", "Value={cp_authToken}", ENDITEM, 
		"Name=orderId", "Value={cp_orderId}", ENDITEM, 
		"Name=addressType", "Value=S", ENDITEM, 
		"Name=URL", "Value=/", ENDITEM, 
		"Name=correlationId", "Value={cp_correlationId}", ENDITEM, 
		"Name=taxExemptCheck", "Value=false", ENDITEM, 
		"Name=taxExemptOrgName", "Value=", ENDITEM, 
		"Name=storeId", "Value=10151", ENDITEM, 
		"Name=langId", "Value=-1", ENDITEM, 
		"Name=catalogId", "Value=10051", ENDITEM, 
		"Name=ccf", "Value=true", ENDITEM, 
		"Name=cof", "Value=true", ENDITEM, 
		LAST);

	web_url("RefreshCheckoutCart", 
		"URL=https://{p_hostName}/us-en/shop/RefreshCheckoutCart?ajax=true&crID={cp_correlationId}&storeId=10151&langId=-1&catalogId=10051&ccf=true&cof=true", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html;charset=UTF-8", 
		"Snapshot=t240.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("CP48_CreatePO",LR_AUTO);

	lr_think_time(10);
	web_set_sockets_option("CLOSE_KEEPALIVE_CONNECTIONS","1");
	lr_start_transaction("CP49_SubmitOrder_PO");

	web_submit_data("OrderSubmitServiceCmd", 
		"Action=https://{p_hostName}/us-en/shop/OrderSubmitServiceCmd", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html;charset=UTF-8", 
		"Snapshot=t253.inf", 
		"Mode=HTML", 
		"EncodeAtSign=YES", 
		ITEMDATA, 
		"Name=shipto_firstname", "Value=PerfFirstSMB", ENDITEM, 
		"Name=shipto_lastname", "Value=PerfLastSMB", ENDITEM, 
		"Name=shipto_companyname", "Value={cp_companyName}", ENDITEM, 
		"Name=shipto_address1", "Value=PerfAddress1", ENDITEM, 
		"Name=shipto_address2", "Value=", ENDITEM, 
		"Name=shipto_city", "Value={p_city}", ENDITEM, 
		"Name=shipto_state", "Value={p_state}", ENDITEM, 
		"Name=shipto_stateprovince", "Value={p_state}", ENDITEM, 
		"Name=shipto_zipcode", "Value={p_zipCode}", ENDITEM, 
		"Name=shipto_country", "Value=US", ENDITEM, 
		"Name=shipto_phonenumber", "Value=1234567890", ENDITEM, 
		"Name=isBusinessPurchase", "Value=true", ENDITEM, 
		"Name=shippingContactFirstName", "Value=PerfFirstSMB", ENDITEM, 
		"Name=shippingContactLastName", "Value=PerfLastSMB", ENDITEM, 
		"Name=shippingCompanyName", "Value={cp_companyName}", ENDITEM, 
		"Name=shippingAddress1", "Value=PerfAddress1", ENDITEM, 
		"Name=shippingAddress2", "Value=", ENDITEM, 
		"Name=shippingCity", "Value={p_city}", ENDITEM, 
		"Name=shippingState", "Value={p_state}", ENDITEM, 
		"Name=shippingZip", "Value={p_zipCode}", ENDITEM, 
		"Name=shippingPhoneNumber", "Value=1234567890", ENDITEM, 
		"Name=billingContactFirstName", "Value=PerfFirstSMB", ENDITEM, 
		"Name=billingContactLastName", "Value=PerfLastSMB", ENDITEM, 
		"Name=billto_NickName", "Value=", ENDITEM, 
		"Name=billto_firstname", "Value=PerfFirstSMB", ENDITEM, 
		"Name=billto_lastname", "Value=PerfLastSMB", ENDITEM, 
		"Name=billto_address1", "Value=PerfAddress1", ENDITEM, 
		"Name=billto_address2", "Value=", ENDITEM, 
		"Name=billto_city", "Value={p_city}", ENDITEM, 
		"Name=billto_state", "Value={p_state}", ENDITEM, 
		"Name=billto_stateprovince", "Value={p_state}", ENDITEM, 
		"Name=billto_zipcode", "Value={p_zipCode}", ENDITEM, 
		"Name=billto_country", "Value=US", ENDITEM, 
		"Name=billto_phone_number", "Value=1234567890", ENDITEM, 
		"Name=confirmationEmail", "Value={cp_userEmail}", ENDITEM, 
		"Name=addressId", "Value={cp_addressId}", ENDITEM, 
		"Name=logonID", "Value={cp_userEmail}", ENDITEM, 
		"Name=safeTechSessionId", "Value={cp_correlationId}", ENDITEM, 
		"Name=paymentType", "Value=payorder", ENDITEM, 
		"Name=ani", "Value=8889994747", ENDITEM, 
		"Name=isSmbOrder", "Value=true", ENDITEM, 
		"Name=isPartnerAgentOrder", "Value=true", ENDITEM, 
		"Name=partnerLocId", "Value=10259725", ENDITEM, 
		"Name=partnerRepId", "Value=10259725", ENDITEM, 
		"Name=partnerPO", "Value=", ENDITEM, 
		"Name=partnerName", "Value=United Testing Systems, Inc.", ENDITEM, 
		"Name=partnerCity", "Value=Fullerton", ENDITEM, 
		"Name=partnerState", "Value=CA", ENDITEM, 
		"Name=partnerZip", "Value=92831", ENDITEM, 
		"Name=po_number", "Value=PerfPO{p_pOrder}", ENDITEM, 
		"Name=billto_companyname", "Value={cp_companyName}", ENDITEM, 
		"Name=billto_phoneno", "Value=1234567890", ENDITEM, 
		"Name=orderId", "Value={cp_orderId}", ENDITEM, 
		"Name=ormOrderId", "Value={cp_orderNo}", ENDITEM, 
		"Name=ormorder", "Value={cp_orderNo}", ENDITEM, 
		"Name=aoID", "Value=", ENDITEM, 
		"Name=taxCheck", "Value=0", ENDITEM, 
		"Name=selectedShipMethod", "Value=12056", ENDITEM, 
		"Name=paymenttype", "Value=payorder", ENDITEM, 
		"Name=chkSCLimit", "Value=true", ENDITEM, 
		"Name=policyId", "Value=", ENDITEM, 
		"Name=storeId", "Value=10151", ENDITEM, 
		"Name=langId", "Value=-1", ENDITEM, 
		"Name=catalogId", "Value=10051", ENDITEM, 
		"Name=ccf", "Value=true", ENDITEM, 
		"Name=cof", "Value=true", ENDITEM, 
		LAST);

	web_submit_data("OrderShippingBillingConfirmationView", 
		"Action=https://{p_hostName}/webapp/wcs/stores/servlet/OrderShippingBillingConfirmationView", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html;charset=UTF-8", 
		"Snapshot=t254.inf", 
		"Mode=HTML", 
		"EncodeAtSign=YES", 
		ITEMDATA, 
		"Name=langId", "Value=-1", ENDITEM, 
		"Name=storeId", "Value=10151", ENDITEM, 
		"Name=catalogId", "Value=10051", ENDITEM, 
		"Name=orderId", "Value={cp_orderId}", ENDITEM, 
		"Name=shipmentTypeId", "Value=1", ENDITEM, 
		"Name=emailSender", "Value={cp_userEmail}", ENDITEM, 
		"Name=sessionKey", "Value=", ENDITEM, 
		"Name=paymenttype", "Value=payorder", ENDITEM, 
		"Name=corelID", "Value={cp_orderNo}_{cp_time}", ENDITEM, 
		"Name=totalAdjValue", "Value=0", ENDITEM, 
		LAST);

	web_url("HPServices_9", 
		"URL=https://{p_hostName}/us-en/shop/HPServices?langId=-1&storeId=10151&catalogId=10051&_=1527254418422&action=cupis&catentryId=&modelId=", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html;charset=UTF-8", 
		"Referer=https://{p_hostName}/webapp/wcs/stores/servlet/OrderShippingBillingConfirmationView", 
		"Snapshot=t258.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("FDPromotionCmd", 
		"Action=https://{p_hostName}/us-en/shop/FDPromotionCmd", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html;charset=UTF-8", 
		"Referer=https://{p_hostName}/webapp/wcs/stores/servlet/OrderShippingBillingConfirmationView", 
		"Snapshot=t259.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		"Name=orderId", "Value={cp_orderId}", ENDITEM, 
		"Name=requesttype", "Value=ajax", ENDITEM, 
		LAST);

	lr_end_transaction("CP49_SubmitOrder_PO",LR_AUTO);
	
	//Logout();
	lr_exit(LR_EXIT_MAIN_ITERATION_AND_CONTINUE,LR_AUTO);
	
	return 0;
}
